- name: Install catalogue component
  hosts: catalogue
  become: yes
  tasks:
    - name: Setup NPM source
      ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

    - name: Install Node.js
      ansible.builtin.yum:
        name: nodejs
        state: present

    - name: Check if roboshop user exists
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true

    - name: Create roboshop user if it doesn't exist
      ansible.builtin.user:
        name: roboshop
      when: output.rc != 0

    - name: Check if /app directory exists
      ansible.builtin.stat:
        path: /app
      register: directory

    - name: Create /app directory if it doesn't exist
      ansible.builtin.file:
        path: /app
        state: directory
      when: directory.stat.exists == False

    - name: Download the catalogue artifacts
      ansible.builtin.get_url:
        url: "https://roboshop-builds.s3.amazonaws.com/catalogue.zip"
        dest: "/tmp/catalogue.zip"

    - name: Extract the catalogue application code to /app directory
      ansible.builtin.unarchive:
        src: "/tmp/catalogue.zip"
        dest: "/app"
        remote_src: yes

    - name: Install application dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: Copy catalogue service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reexec: yes

    - name: Copy MongoDB repo to yum.repos.d
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install MongoDB
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Load catalogue data
      ansible.builtin.command: mongo --host mongodb.joinsankardevops.online </app/schema/catalogue.js

    - name: Restart the catalogue service
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: true
