---
- name: Install MongoDB component
  hosts: mongodb
  become: yes
  tasks:
    - name: Copy MongoDB repo to yum
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install MongoDB
      ansible.builtin.yum:
        name: mongodb-org
        state: present
    - name: start and enable momgodb
      ansible.builtin.service:
       name: momgod
       state: started
       enabled: yes
    - name: enabled remote connections mongodb
       ansible.builtin.replaced:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
   - name: Restart MongoDB service
      ansible.builtin.systemd:
        name: mongod
        state: restarted
