- name: install web component
  hosts: web
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: installed

    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Remove html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

    - name: Create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: directory

    - name: Download the web artifacts
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/web.zip
        dest: /tmp/web.zip

    - name: Extract the web application code to html directory
      ansible.builtin.unarchive:
        src: /tmp/web.zip
        dest: /usr/share/nginx/html/
        remote_src: yes

    - name: Copy roboshop.conf
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: Check nginx configuration
      ansible.builtin.command:
        cmd: nginx -t
      register: nginx_config_test
      ignore_errors: yes

    - name: Debug nginx configuration test output
      ansible.builtin.debug:
        msg: "{{ nginx_config_test.stdout }}"

    - name: Fail if nginx configuration test failed
      ansible.builtin.fail:
        msg: "Nginx configuration test failed. Error: {{ nginx_config_test.stdout }}"
      when: nginx_config_test.rc != 0

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: nginx_config_test.rc == 0
